### ISSUE TITLE
Fail at running action

### ISSUE THREAD

**Issue by hernan-peralta** [KengoTODA/actions-setup-docker-compose#387]
Hello, I was using a workflow with this action and it worked correctly up until last week, I think this PR caused the issue: https://github.com/KengoTODA/actions-setup-docker-compose/pull/379

Here's the console output error:
```
[Main/build] ⭐  Run KengoTODA/actions-setup-docker-compose@main
INFO[0000]   ☁  git clone 'https://github.com/KengoTODA/actions-setup-docker-compose' # ref=main 
[Main/build]   ❌  Failure - KengoTODA/actions-setup-docker-compose@main
Error: The runs.using key in action.yml must be one of: [composite docker node12], got node16
```

**Comment by KengoTODA** [comment]
Yes now this Action uses `node16` as runtime. If you're using GHES, use v3.0 or later. According to the official doc, 3.0 and later already support `node16` as runtime:

https://docs.github.com/en/enterprise-server@3.0/actions/creating-actions/metadata-syntax-for-github-actions#runs-for-javascript-actions

**Comment by hernan-peralta** [comment]
Thank you for the reply. I'm actually using [act](https://github.com/nektos/act), so I guess it must be some kind of incompatibility then. I temporarily fixed it by replacing the docker-compose call in main.yml with an equivalent docker command.

**Comment by KengoTODA** [comment]
I believe that this issue has been fixed on the act side by https://github.com/nektos/act/issues/910
