### ISSUE TITLE
error message when using package

### ISSUE THREAD

**Issue by maikelmclauflin** [KengoTODA/actions-setup-docker-compose#69]
```
Error: The `add-path` command is deprecated and will be disabled on November 16th. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```

not sure where this is used but it comes up when i try to use the package in github action

**Comment by KengoTODA** [comment]
This action runs `core.addPath()` at https://github.com/KengoTODA/actions-setup-docker-compose/blob/8cc9a6376a891af4da12d82611c0013f3644774e/src/main.ts#L10

As announced as below, we need to use `@actions/core v1.2.6` or later. 

> Action authors who are using the toolkit should update the @actions/core package to v1.2.6 or greater to get the updated addPath and exportVariable functions.
> https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

And in the main branch, [we've already applied this version](https://github.com/KengoTODA/actions-setup-docker-compose/blob/8cc9a6376a891af4da12d82611c0013f3644774e/package.json#L28). So using the version `ad6048480184cd0e09ba039cf7842c8262929cbb` or later will fix it.

**Comment by maikelmclauflin** [comment]
is it perhaps referencing something incorrectly?
```
Run KengoTODA/actions-setup-docker-compose@8cc9a6376a891af4da12d82611c0013f3644774e
/bin/uname -s
/bin/uname -m
Linux
x86_64
/bin/chmod +x /home/runner/work/_temp/81caff09-275a-48b7-95d8-059ed8111518
Error: Unable to process command '::add-path::/home/runner/work/_temp/81caff09-275a-48b7-95d8-059ed8111518' successfully.
Error: The `add-path` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```

```
Run KengoTODA/actions-setup-docker-compose@18153c6e0425d2c1b2371d94f4c9c2942dd5e514
/bin/uname -s
/bin/uname -m
Linux
x86_64
/bin/chmod +x /home/runner/work/_temp/876ea4f9-9636-4314-bd3e-afe2ab5d3600
Error: Unable to process command '::add-path::/home/runner/work/_temp/876ea4f9-9636-4314-bd3e-afe2ab5d3600' successfully.
Error: The `add-path` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```

**Comment by KengoTODA** [comment]
Have you upgraded your self-hosted runner? According to the blog, it should be upgraded to recent release.

**Comment by maikelmclauflin** [comment]
yes, i am using `runs-on: ubuntu-latest` if that is what you are asking about

**Comment by KengoTODA** [comment]
I found the root cause, the dependabot bumped up the dependencies, but our workflow didn't run `npm run all` so the files in `/dist` directory wasn't updated.

I pushed 92cbaf8 which contains the fix, could you have a try with this Git hash?

**Comment by maikelmclauflin** [comment]
looks like that worked. thanks!
